# Generated by Django 5.1.7 on 2025-04-01 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('FICTION', 'Fiction'), ('NON-FICTION', 'Non-fiction'), ('MYSTERY', 'Mystery'), ('SCIENCE FICTION', 'Science Fiction'), ('ROMANCE', 'Romance'), ('HORROR', 'Horror'), ('BIOGRAPHY', 'Biography'), ('POETRY', 'Poetry'), ('OTHER', 'other')], max_length=30)),
                ('isbn', models.CharField(max_length=12, unique=True, verbose_name='ISBN')),
                ('publication_date', models.DateField()),
                ('average_rating', models.DecimalField(decimal_places=3, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
