# Generated by Django 4.2.19 on 2025-06-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/default.jpg', upload_to='books/'),
        ),
    ]
