# Generated by Django 4.2.19 on 2025-06-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('SCRIPTURE', 'Scripture'), ('FICTION', 'Fiction'), ('NON-FICTION', 'Non-fiction'), ('MYSTERY', 'Mystery'), ('SCIENCE FICTION', 'Science Fiction'), ('ROMANCE', 'Romance'), ('HORROR', 'Horror'), ('BIOGRAPHY', 'Biography'), ('POETRY', 'Poetry'), ('OTHER', 'other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books/'),
        ),
    ]
